openapi: '3.0.2'
info:
  title: Kanban App Project API Specs (Rest)
  version: '1.0'
components:
  parameters:
    pathBoardIdParam:
      name: boardId
      in: path
      schema:
        type: string
      required: true
    pathColumnIdParam:
      name: columnId
      in: path
      schema:
        type: string
      required: true
    pathCardIdParam:
      name: cardId
      in: path
      schema:
        type: string
      required: true
  schemas:
    plainResponse:
      type: object
      properties:
        message:
          type: string
paths:
  /api/boards:
    get:
      description: 'Get all user boards'
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        thumbnail_url:
                          type: string
                        user:
                          type: object
                          properties:
                            id:
                              type: string
                            name:
                              type: string
                        opened_at:
                          type: string
                        links:
                          type: object
                          properties:
                            self:
                              type: object
                              properties:
                                href:
                                  type: string
    post:
      description: 'Create board'
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      board:
                        type: object
                        properties:
                          id:
                            type: string
  /api/boards/{id}:
    get:
      description: 'Get board details'
      parameters:
        - $ref: '#/components/parameters/pathBoardIdParam'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      created_at:
                        type: string
                      updated_at:
                        type: string
                      user:
                        type: object
                        properties:
                          id:
                            type: string
                          name:
                            type: string
                      links:
                        type: object
                        properties:
                          self:
                            type: object
                            properties:
                              href:
                                type: string
                          columns:
                            type: object
                            properties:
                              href:
                                type: string
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/plainResponse'
    patch:
      description: 'Rename board'
      parameters:
        - $ref: '#/components/parameters/pathBoardIdParam'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/plainResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/plainResponse'
    delete:
      description: 'Delete board'
      parameters:
        - $ref: '#/components/parameters/pathBoardIdParam'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/plainResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/plainResponse'
  /api/boards/{boardId}/columns:
    get:
      description: 'Get all columns inside board'
      parameters:
        - $ref: '#/components/parameters/pathBoardIdParam'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        order:
                          type: number
                        links:
                          type: object
                          properties:
                            self:
                              type: object
                              properties:
                                href:
                                  type: string
                            move:
                              type: object
                              properties:
                                href:
                                  type: string
    post:
      description: 'Create column inside board'
      parameters:
        - $ref: '#/components/parameters/pathBoardIdParam'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                order:
                  type: number
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      column:
                        type: object
                        properties:
                          id:
                            type: string
  /api/columns/{columnId}:
    get:
      description: 'Get column details'
      parameters:
        - $ref: '#/components/parameters/pathBoardIdParam'
        - $ref: '#/components/parameters/pathColumnIdParam'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      created_at:
                        type: string
                      updated_at:
                        type: string
                      order:
                        type: number
                      cards:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                            body:
                              type: string
                            links:
                              type: object
                              properties:
                                self:
                                  type: object
                                  properties:
                                    href:
                                      type: string
                                move:
                                  type: object
                                  properties:
                                    href:
                                      type: string
                  links:
                    type: object
                    properties:
                      self:
                        type: object
                        properties:
                          href:
                            type: string
                      move:
                        type: object
                        properties:
                          href:
                            type: string
    patch:
      description: 'Patch column'
      parameters:
        - $ref: '#/components/parameters/pathBoardIdParam'
        - $ref: '#/components/parameters/pathColumnIdParam'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/plainResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/plainResponse'
    delete:
      description: 'Delete column'
      parameters:
        - $ref: '#/components/parameters/pathBoardIdParam'
        - $ref: '#/components/parameters/pathColumnIdParam'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/plainResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/plainResponse'
  /api/columns/{columnId}/move:
    patch:
      description: 'Move column order inside board'
      parameters:
        - $ref: '#/components/parameters/pathBoardIdParam'
        - $ref: '#/components/parameters/pathColumnIdParam'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                order:
                  type: number
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/plainResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/plainResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/plainResponse'
  /api/columns/{columnId}/cards:
    get:
      description: 'Get all cards within column'
      parameters:
        - $ref: '#/components/parameters/pathColumnIdParam'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        body:
                          type: string
                        links:
                          type: object
                          properties:
                            self:
                              type: object
                              properties:
                                href:
                                  type: string
                            move:
                              type: object
                              properties:
                                href:
                                  type: string
    post:
      description: 'Create card inside column'
      parameters:
        - $ref: '#/components/parameters/pathColumnIdParam'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/plainResponse'
  /api/cards/{cardId}:
    get:
      description: 'Get card details'
      parameters:
        - $ref: '#/components/parameters/pathColumnIdParam'
        - $ref: '#/components/parameters/pathCardIdParam'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      body:
                        type: string
                      created_at:
                        type: string
                      updated_at:
                        type: string
                      links:
                        type: object
                        properties:
                          self:
                            type: object
                            properties:
                              href:
                                type: string
                          move:
                            type: object
                            properties:
                              href:
                                type: string
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/plainResponse'
    patch:
      description: 'Patch card'
      parameters:
        - $ref: '#/components/parameters/pathColumnIdParam'
        - $ref: '#/components/parameters/pathCardIdParam'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/plainResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/plainResponse'
    delete:
      description: 'Delete card'
      parameters:
        - $ref: '#/components/parameters/pathColumnIdParam'
        - $ref: '#/components/parameters/pathCardIdParam'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/plainResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/plainResponse'
  /api/cards/{cardId}/move:
    patch:
      description: 'Move card to column'
      parameters:
        - $ref: '#/components/parameters/pathColumnIdParam'
        - $ref: '#/components/parameters/pathCardIdParam'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                column_id:
                  type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/plainResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/plainResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/plainResponse'
